// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type SignupInput struct {
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	Country       *string `json:"country,omitempty"`
	Job           *string `json:"job,omitempty"`
	ProfilePicURL *string `json:"profilePicURL,omitempty"`
}

type User struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	Country       *string `json:"country,omitempty"`
	Job           *string `json:"job,omitempty"`
	ProfilePicURL *string `json:"profilePicURL,omitempty"`
}
