// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Bill struct {
	BillID      int32   `json:"billID"`
	Company     string  `json:"company"`
	CreatedAt   string  `json:"createdAt"`
	TotalAmount float64 `json:"totalAmount"`
}

type BillDetails struct {
	BillID    int32        `json:"billID"`
	CreatedAt string       `json:"createdAt"`
	BillType  string       `json:"billType"`
	Notes     *string      `json:"notes,omitempty"`
	Subtotal  *float64     `json:"subtotal,omitempty"`
	Tax       *float64     `json:"tax,omitempty"`
	Discount  *float64     `json:"discount,omitempty"`
	Total     float64      `json:"total"`
	User      *UserProfile `json:"user"`
	Items     []*BillItem  `json:"items"`
	Payment   *Payment     `json:"payment,omitempty"`
	Company   *string      `json:"company,omitempty"`
}

type BillItem struct {
	Description string  `json:"description"`
	Quantity    int32   `json:"quantity"`
	UnitPrice   float64 `json:"unitPrice"`
	TotalPrice  float64 `json:"totalPrice"`
}

type BillPaginationResult struct {
	TotalCount int32   `json:"totalCount"`
	Bills      []*Bill `json:"bills,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Payment struct {
	Amount float64 `json:"amount"`
	Method string  `json:"method"`
	PaidAt string  `json:"paidAt"`
}

type Query struct {
}

type SignupInput struct {
	Email         string  `json:"email"`
	Password      string  `json:"password"`
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	Company       *string `json:"company,omitempty"`
	ProfilePicURL *string `json:"profilePicURL,omitempty"`
}

type User struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	PhoneNumber   *string `json:"phoneNumber,omitempty"`
	Company       *string `json:"company,omitempty"`
	ProfilePicURL *string `json:"profilePicURL,omitempty"`
}

type UserProfile struct {
	FirstName   *string `json:"firstName,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Company     *string `json:"company,omitempty"`
}
